# Generated by Django 5.1.3 on 2024-11-12 00:44

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_name",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("product_url", models.URLField(blank=True, max_length=350, null=True)),
                ("image_url", models.URLField(blank=True, max_length=350, null=True)),
                (
                    "product_price",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "slug",
                    models.CharField(
                        blank=True, max_length=350, null=True, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
