# Generated by Django 5.1.3 on 2024-11-19 02:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["name"],
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(default="", max_length=150, unique=True),
        ),
    ]
