# Generated by Django 5.1.3 on 2024-11-20 00:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_alter_category_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="categoty",
            new_name="category",
        ),
    ]
